files:
  "/etc/nginx/conf.d/types_hash.conf":
    content: |
      types_hash_max_size 2048;
      types_hash_bucket_size 128;

container_commands:
  01_reload_nginx:
    command: "service nginx reload"
